baseURL = "https://jan.trejbal.land/"
languageCode = "en-us"
title = "Jan Trejbal"
theme = "winning"
googleAnalytics = "UA-129134762-2"
enableRobotsTXT = true

disableKinds = ["RSS"]
defaultContentLanguage = "en"

[blackfriday]
    fractions = false

[taxonomies]

[author]
    name = "Jan Trejbal"
    email = "jan@trejbal.land"
